### PR TITLE
support dataset rows more then max(int32_t) (add CMAKE option)

### PR DESCRIPTION
**Pull request by junpeng0715**
related to #5454 , add a CMAKE option to switch int32 and int64

### CODE REVIEW

**Comment by guolinke** [comment]
@shiyu1994 can you help to review this PR?

**Comment by guolinke** [comment]
@junpeng0715 can you also add a CI test, to build with int64_t type and run some tests?

**Comment by guolinke** [comment]
> @junpeng0715 can you also add a CI test, to build with int64_t type and run some tests?

Oh, I saw the test, thank you!

**Review by jameslamb — CHANGES_REQUESTED** [review]
I'd like a chance to also review these quite impactful changes. Before I do...why was a new PR opened instead of just pushing changes to #5454? Can we now close #5454?

Also, please check you `.gitconfig`...it looks like many of your commits are not tied to your GitHub account. See https://github.com/microsoft/LightGBM/pull/5532#issuecomment-1274032708.

**Comment by junpeng0715** [comment]
@microsoft-github-policy-service agree [company="ACN"]

**Comment by junpeng0715** [comment]
@microsoft-github-policy-service agree company="ACN"

**Comment by junpeng0715** [comment]
> I'd like a chance to also review these quite impactful changes. Before I do...why was a new PR opened instead of just pushing changes to #5454? Can we now close #5454?

@jameslamb It is a PR without Cmake Option modification as a backup. I think we can close it.

> Also, please check you `.gitconfig`...it looks like many of your commits are not tied to your GitHub account. See [#5532 (comment)](https://github.com/microsoft/LightGBM/pull/5532#issuecomment-1274032708).

Thank you for your tips, modified it!

**Comment by jameslamb** [comment]
Ok thanks, I closed #5554.

In the future, please just push new commits in response to reviewers' comments, instead of opening new PRs. That keeps all of the conversation focused in one place, and ensures that other conversations threads that linked to the work you were doing don't need to now to link to multiple very-similar pull requests.

**Comment by junpeng0715** [comment]
@guolinke @jameslamb @shiyu1994 
Hi Guys
How to trigger the pipeline for R-packages?CUDA? etc. I think there were some errors.

**Comment by junpeng0715** [comment]
Hi @guolinke @shiyu1994
Can you give some suggestions on how to fix CUDA version and R-package(windows-lastest) issues?
image

**Comment by junpeng0715** [comment]
Hi @jameslamb 
It seems reviewers has been deleted when I click the Re-request review button.
Could you help to re-add the reviewers?
image

And could you help to trigger the pipelines?
Thank you very much!

File: python-package/lightgbm/basic.py [hunk 1]
```diff
@@ -821,6 +833,9 @@ def predict(
         validate_features : bool, optional (default=False)
             If True, ensure that the features used to predict match the ones used to train.
             Used only if data is pandas DataFrame.
+        use_int64 : bool, optional (default=False)
+            If True, support dataset rows more then max(int32_t).
+            Need to build with cmake option USE_DATASET_INT64 for lightGBM.
```
Comment (StrikerRUS) [inline python-package/lightgbm/basic.py:838]: I think instead of introducing a new param in a lot of places we can define a new C API function that will return whether LightGBM was compiled with int64 support or not.

Comment (StrikerRUS) [reply python-package/lightgbm/basic.py:838]: For example, in XGBoost:
https://github.com/dmlc/xgboost/blob/97c3a80a346828165c57225929657461bcaeeda2/include/xgboost/c_api.h#L65-L72
https://github.com/dmlc/xgboost/blob/8d4038da57cd06070677460d138a648c132665b1/src/c_api/c_api.cc#L59-L112

**Comment by junpeng0715** [comment]
Hi @guolinke  @jameslamb @StrikerRUS @shiyu1994
Could you please help review for this PR?
And do you have a plan to merge this?

I also made a PR to SynapseML:https://github.com/microsoft/SynapseML/pull/1684 to support LGBM int64, this is depend on the top repo of LGBM. So Could you let me know the plan for this feature PR?

**Comment by jameslamb** [comment]
> Could you please help review for this PR?

We will review this once it is passing CI. Please fix the failing `lint` task (https://github.com/microsoft/LightGBM/actions/runs/3327507460/jobs/5510896951) and Azure DevOps jobs (https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=13781&view=results).

CUDA build have also been blocked in this repo for 9 days now...we are blocked waiting on #5546. Sorry for the inconvenience.

File: tests/python_package_test/test_dask.py [hunk 2]
```diff
@@ -57,7 +57,8 @@
 pytestmark = [
     pytest.mark.skipif(getenv('TASK', '') == 'mpi', reason='Fails to run with MPI interface'),
     pytest.mark.skipif(getenv('TASK', '') == 'gpu', reason='Fails to run with GPU interface'),
-    pytest.mark.skipif(getenv('TASK', '') == 'cuda_exp', reason='Fails to run with CUDA Experimental interface')
+    pytest.mark.skipif(getenv('TASK', '') == 'cuda_exp', reason='Fails to run with CUDA Experimental interface'),
+    pytest.mark.skipif(getenv('TASK', '') == 'int64', reason='Fails to run with Dataset rows with int64 interface')
```
Comment (jameslamb) [inline tests/python_package_test/test_dask.py:61]: Can you please explain *specifically* which Dask tests failed as a result of the changes in this PR? The Dask tests are the most thorough tests of distributed training in this repo, so I'm very nervous about skipping them on a PR that makes such invasive changes.

Comment (junpeng0715) [reply tests/python_package_test/test_dask.py]: Thank you. 
I enabled the dask tests for int64

**Comment by junpeng0715** [comment]
> > Could you please help review for this PR?
> 
> We will review this once it is passing CI. Please fix the failing `lint` task (https://github.com/microsoft/LightGBM/actions/runs/3327507460/jobs/5510896951) and Azure DevOps jobs (https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=13781&view=results).
> 
> CUDA builds have also been blocked in this repo for 9 days now...we are blocked waiting on #5546. Sorry for the inconvenience.

I will check  `lint` task, I think failing DevOps jobs related to MacOS is working on #5555, CUDA issue is #5546  as you said.
There also hava some R-package failings in this PR and other PR,  unrelated to my codes.

**Comment by junpeng0715** [comment]
Hi @jameslamb 
The Static Analysis issue for this PR has been resolved.

The block issues are as below, am I right?
R-package: #5563 
MacOS : #5555 
CUDA: #5546

**Comment by jameslamb** [comment]
> The block issues are as below, am I right?

No. #5555 is not a blocking issue.

The following need to be fixed before any pull requests in this repo will build successfully.

* CUDA jobs: #5546
* support for OpenMP 15+ on macOS: #5549
* MikTex setup on Windows: #5562

Fixing #5546 requires manual action that only @shiyu1994 can do. #5549 and #5562 will be fixed by #5563.

**Comment by junpeng0715** [comment]
> > The block issues are as below, am I right?
> 
> No. #5555 is not a blocking issue.
> 
> The following need to be fixed before any pull requests in this repo will build successfully.
> 
> * CUDA jobs: [[ci] CUDA CI jobs are broken: "driver/library version mismatch" #5546](https://github.com/microsoft/LightGBM/issues/5546)
> * support for OpenMP 15+ on macOS: [CMake can't find libomp on Apple M1 #5549](https://github.com/microsoft/LightGBM/issues/5549)
> * MikTex setup on Windows: [[ci] [R-package] windows-latest CI jobs are broken: "initexmf.exe" failing #5562](https://github.com/microsoft/LightGBM/issues/5562)
> 
> Fixing #5546 requires manual action that only @shiyu1994 can do. #5549 and #5562 will be fixed by #5563.

Thank you @jameslamb ! I understand clearly now!

**Comment by jameslamb** [comment]
@junpeng0715 The CI issues have been fixed. Please merge latest `master`  into this branch so we can review.

**Comment by junpeng0715** [comment]
> @junpeng0715 The CI issues have been fixed. Please merge latest `master` into this branch so we can review.

@jameslamb Merged the lastest `master`. Got a new error in Linux inference[Initialize job] , "File not found: 'docker'"

**Comment by junpeng0715** [comment]
@jameslamb 
I resolved the conflicts, could you help trigger pipeline ?

**Comment by jameslamb** [comment]
> could you help trigger pipeline

sure, re-triggered. As I mentioned previously (https://github.com/microsoft/LightGBM/pull/5540#issuecomment-1282385233), you could also consider making a separate, small, non-controversial contribution (like one of the items from #5313) so that you wouldn't be considered a first-time contributor any more and would need to `@` us every time you want the CI jobs to run.

**Comment by junpeng0715** [comment]
Hi @jameslamb 
Got R-package error, I think it is also an OpenMP issue

`test-omp.c:1:10: fatal error: 'omp.h' file not found`
`#include <omp.h>`
`         ^~~~~~~`
`1 error generated.`
`*** OpenMP not supported! data.table uses OpenMP to automatically`

**Comment by jameslamb** [comment]
> We will move this PR forward,

Are you still interested in pursuing this PR? It's been 4 months since the most recent commit.

**Comment by jameslamb** [comment]
> We will move this PR forward,

@guolinke are you still interested in pursuing this PR? It's been 4 months since the most recent commit.

**Comment by guolinke** [comment]
I think we can work on the 4.0.0 release first, then revisit these PRs after that. cc @shiyu1994 .
 
> > We will move this PR forward,
> 
> 
> 
> @guolinke are you still interested in pursuing this PR? It's been 4 months since the most recent commit.

**Comment by sinhrks** [comment]
Thx for following up. Is it ok for me to prepare another PR to rebase this?

**Comment by guolinke** [comment]
> Thx for following up. Is it ok for me to prepare another PR to rebase this?

Sure, please go ahead.
